### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by liuhewei** [ddiachkov/sublime-yaml-nav#12]
https://github.com/ddiachkov/sublime-yaml-nav/blob/master/yaml_nav.py#L77

Should remove a "self" here? For example, `self.on_load(view)`

I have an error report on this line, under ST3 Dev build 3109.

**Comment by ddiachkov** [comment]
Yeah, you are right! This is an error.

**Comment by pokidovea** [comment]
Ping. It is really annoying

**Comment by FichteFoll** [comment]
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 180, in on_new
    callback.on_new(v)
  File "yaml_nav in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\YAML Nav.sublime-package", line 77, in on_new
TypeError: on_load() takes 2 positional arguments but 3 were given
```
