### ISSUE TITLE
TypeError: on_load() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by dannote** [ddiachkov/sublime-yaml-nav#16]
Hello!

Got this error after recent update on Sublime Text 3 (Build 3175):

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 403, in on_new
    callback.on_new(v)
  File "/Users/dannote/Library/Application Support/Sublime Text 3/Installed Packages/YAML Nav.sublime-package/yaml_nav.py", line 77, in on_new
    self.on_load(self, view)
TypeError: on_load() takes 2 positional arguments but 3 were given
```

**Comment by ConorSheehan1** [comment]
Possibly the same as https://github.com/ddiachkov/sublime-yaml-nav/issues/12? PR https://github.com/ddiachkov/sublime-yaml-nav/pull/14 should solve it.
It's been open for 3 years though, so I'm not holding my breath :(
